### ISSUE TITLE
helm-swoop-line-number-face not working

### ISSUE THREAD

**Issue by naclander** [emacsorphanage/helm-swoop#121]
I have the following configuration:

```lisp
(require 'helm-swoop)
(setq helm-swoop-use-line-number-face t)
(set-face-foreground 'helm-swoop-line-number-face "blue")
(set-face-background 'helm-swoop-line-number-face "blue")
```
When running `helm-swoop` I expect to see **something** different in the line numbers face, but that doesn't seem to work. Am I configuring something incorrectly?

**Comment by it3ration** [comment]
I am also seeing this, it doesn't appear to work properly at present.

**Comment by kenoh** [comment]
You should check if you have `helm-swoop-speed-or-color` set to `t`; with `nil` it does not work for me.

**Comment by cireu** [comment]
Please set `helm-swoop-speed-or-color` to `t`
