### ISSUE TITLE
next-history-element cannot insert word under cursor

### ISSUE THREAD

**Issue by ahlearn** [emacsorphanage/helm-swoop#122]
In other helm use cases, next-history-element can be used to [insert word under cursor](https://emacs.stackexchange.com/a/17764/12987).

But in helm-swoop, the command wrongly insert word at the beginning of current line?

**Comment by cireu** [comment]
Please try `(define-key helm-swoop-map [remap next-history-element] #'helm-swoop-yank-thing-at-point)`
