### ISSUE TITLE
Maintainance

### ISSUE THREAD

**Issue by kngwyu** [emacsorphanage/helm-swoop#143]
This repository is no longer maintained and I saw @ShingoFukuyama said that he's looking for a new maintainer https://twitter.com/fokotate/status/1126078672689958912 .
So is there anyone who is willing to maintain this repository?

I'm a heavy user of helm-swoop but I don't have knowledge about elisp and helm enough to be a maintainer.
So I think it's great if anyone with experiences of developing helm library contacts @ShingoFukuyama to be a maintainer of helm-swoop.

**Comment by JesusMtnez** [comment]
@ShingoFukuyama I would be interested in helping maintaining `helm-swoop` project. Right now, I'm the maintainer of [`emacs-dashboard`](https://github.com/emacs-dashboard/emacs-dashboard) projects. I'm not an  Emacs Lisp expert, but I am a heavy helm user, and I'm willing to learn about `helm` code and this seems to be a great opportunity.

**Comment by cireu** [comment]
I create a fork of this and fix some issue. Would someone want to try this? 

https://github.com/cireu/helm-swoop

**Comment by cireu** [comment]
@kngwyu Hello, I can help maintain this package now, thanks for your attention.

**Comment by kngwyu** [comment]
@cieu
Great, thanks!
