### ISSUE TITLE
RFI/Hep sought: stop defaulting to thing at point?

### ISSUE THREAD

**Issue by rileyrg** [emacsorphanage/helm-swoop#177]
afaik the helm "norm" is not to pick up thing at point and to fetch thing at point using M-n if you so want. Can I configure helm-swoop to adhere to this?

**Comment by cireu** [comment]
You may use

```elisp
(setq helm-swoop-pre-input-function (lambda () ""))
```

**Comment by rileyrg** [comment]
Thank you. I later found this here:-

[changing helm-swoop default search term](https://emacs.stackexchange.com/questions/28089/how-do-i-make-helm-swoop-not-default-the-search-to-the-word-at-point?rq=1)
