### ISSUE TITLE
How to avoid "search at point" in helm-swoop

### ISSUE THREAD

**Issue by Gahamelas** [emacsorphanage/helm-swoop#178]
I'd like to use helm-swoop as my to-go search without the feature of searching "at point" (because I want to type my search keywords, and usually I have to delete whichever helm-swoop picked at point). Thanks!

**Comment by conao3** [comment]
How about this configuration (in README sample)?
```emacs-lisp
;; If a symbol or phrase is selected, use it as the initial query.
(setq helm-swoop-pre-input-function
      (lambda ()
        (if mark-active
            (buffer-substring-no-properties (mark) (point))
          "")))
```

**Comment by Gahamelas** [comment]
Would this disable the "at-point" feature?

**Comment by conao3** [comment]
OK, thanks!
