### ISSUE TITLE
Is it possible to compose a buffer using different queries?

### ISSUE THREAD

**Issue by Ypot** [emacsorphanage/helm-swoop#180]
I have just discovered this tool. It is very helpful for me, because it can do a kind of "interactive Sparse Tree" thanks to the multiline behavior.

Just a question: Is it possible to compose a buffer using lines from different helm-swoop queries?

For example: you do "M-4 M-x helm-swoop" and get some parts of "A" buffer.
You repeat "M-4 M-x helm-swoop" with a different query and you get some other parts of the same "A" buffer.
Is it possible to combine those results, so you get a composed buffer that you can edit?

**EDITED: I think I've found how to do that: Selecting different results using C-SPC.

**Comment by conao3** [comment]
Good, you can also use a regexp query.

![Screenshot_2020-05-10_21-10-10](https://user-images.githubusercontent.com/4703128/81499054-8f80f680-9303-11ea-9e1e-388a77989989.png)
