### ISSUE TITLE
Omit line numbers from *Helm Multi Swoop* buffer

### ISSUE THREAD

**Issue by killes** [emacsorphanage/helm-swoop#192]
The result of helm-multi-swoop-projectile is a buffer which lists matches in the individual buffers and gives their line numbers.

I do not need these line numbers as I am using this for .txt files, not programming. Can I remove them somehow?

**Comment by conao3** [comment]
I think can't, currently.

**Comment by killes** [comment]
Thanks, it is not that important.

I read somewhere it would be slow, so I thought removing them would speed things up.
