### ISSUE TITLE
helm-swoop buffer empty until I press up or down

### ISSUE THREAD

**Issue by robert-stuttaford** [emacsorphanage/helm-swoop#195]
Since upgrading to Emacs 27.1.

Other helm buffers (e.g. helm-projectile) render fine.

**Comment by cireu** [comment]
Can you reproduce it in `emacs -Q` with only `helm` and `helm-swoop` loaded?

**Comment by robert-stuttaford** [comment]
Unfortunately, no, I can not. I guess that means it's time to gut my `init.el`?

When I tried, I got this warning, but even so, it works:

```
helm-swoop.el:1696:1:Warning: the following functions are not known to be
    defined: string-trim, string-empty-p
```

**Comment by cireu** [comment]
Oh, I guess someone use these functions without requiring `subr-x`. But I don't think it's the problem, if Emacs missing these functions, it will report an error instead of display nothing.

**Comment by robert-stuttaford** [comment]
Closing, thank you for taking a look :-) I'll shave some yaks here, it's overdue anyway...

https://twitter.com/RobStuttaford/status/1301557165715587072
