### ISSUE TITLE
Obsolete functions in Emacs 29.1

### ISSUE THREAD

**Issue by arifer612** [emacsorphanage/helm-swoop#208]
In Emacs 29.1, the aliases `point-at-bol` and `point-at-eol` are obsolete, and
will raise warnings to use `line-beginning-position`/`pos-bol`, or
`line-end-position`/`pos-eol`, instead, respectively. While this is not a huge
issue at this moment, it might break the project if these aliases get deprecated
in the future. To avoid this from happening, the aliases should either:
1. be re-defined in the project, or
2. be replaced by the actual functions they reference, i.e.,
`line-beginning-position` and `line-end-position`.

For legacy compatibility to around Emacs 20.4, using `line-beginning-position`
and `line-end-position` is the better choice.

I can work up a PR for this if nobody is against the idea of replacing the
aliases `point-at-bol` and `point-at-eol` to the fully qualified functions they
reference, `line-beginning-position` and `line-end-position`, respectively.

**Comment by conao3** [comment]
Nice catch. I am open to this change, can you create a PR?

**Comment by arifer612** [comment]
Sure thing! Just put up the PR :)
