### ISSUE TITLE
Error running timer w

### ISSUE THREAD

**Issue by Enrico68** [emacsorphanage/helm-swoop#36]
When I try helm-swoop a buffer i have this error

```
Error running timer: (file-error "Writing to process" "bad file descriptor" #<process swoop-batch>) [2 times]
```

I am using emacs 24.4.1 (MacPort).

**Comment by conao3** [comment]
Is this still an issue?
It seems to outdated this issue. Please comment if you are still facing this issue.
This issue will be closed this September.
