### ISSUE TITLE
Neotree and Heml-Swoop bug

### ISSUE THREAD

**Issue by gopar** [emacsorphanage/helm-swoop#64]
I noticed that whenever I do a call to `helm-swoop` and I have Neotree visible, there's a bug in which I can't move up or down in the helm-swoop menu. It's basically frozen and it won't work correctly unless I hide Neotree and then call helm-swoop

I made this little function to help me while I get some input from the issue.

```
(defun my-helm-swoop ()
  "Hide neotree when doing helm swoop"
  (interactive)
  ;; if Neotree buffer is visible
  (if (member (get-buffer " *NeoTree*") (mapcar 'window-buffer (window-list)))
      (progn
        (neotree-hide)
        (helm-swoop)
        (neotree-show)
        (switch-window))
    (helm-swoop)))
```

**Comment by blazeeboy** [comment]
@gopar Thanks, I encounter the same bug now,
but the problem is that when you enter helm-swoop and choose a line you'll get back to neotree selected by default

**Comment by gopar** [comment]
@blazeeboy dang, I completely forgot about neotree. I don't use it anymore (switched to projectile). 

Hmm, I don't remember if this is the exact snippet I used (I changed it a few times after the initial one)
