### ISSUE TITLE
Different behaviour of C-w (helm-swoop-yank-word) depending on how fast it is pressed

### ISSUE THREAD

**Issue by sewkokot** [emacsorphanage/helm-swoop#72]
I have bound 'helm-swoop to C-s and set pre-input as nil so when I do C-s C-w (yank symbol at point) very quickly and not that quickly the result is different. For example I have a line:
(defun avy-|goto-conditional ()
the cursor is at | point. If I hit C-s C-w very quickly, the symbol "defun" is yanked in the minibuffer,
while in the slow case the correct "avy-goto-conditional" is submitted for searching.
I suspect that in the first case in the meantime the cursor goes to the begining of line and at that time it grabs the symbol-at-point. Is the moving to the beg of line necessary in the code?

**Comment by sewkokot** [comment]
Could anyone check
assuming no pre-input: (setq helm-swoop-pre-input-function #'ignore)
and a huge buffer (mine init.el is more 21 000 lines) 
if fast pressing (key-sequence bound to helm-swoop) followed by C-w 
(helm-swoop-yank-thing-at-point) gives wrong thing at point?
To be more precise this different behaviour happen when no *helm-swoop* buffer appears. If this *helm-swoop* buffer has enough time to appear then C-w yanks the correct symbol-at-point. Operating on small buffers/files the time to find the results is short show it works ok.

**Comment by cireu** [comment]
A interesting feature request but maybe not useful.

@conao3  your opinion?

**Comment by cireu** [comment]
Close because it makes users confusing if behaviour depends on the how they hit the key.
