### ISSUE TITLE
Font locking in swoop results buffer

### ISSUE THREAD

**Issue by frobbit** [emacsorphanage/helm-swoop#85]
The lines in the swoop results buffer are sometimes not font locked the same as the buffer being searched over (in my case elisp and python source files), but sometimes they do have the same font locking. I've noticed that the first lines of the swoop results often have the correct font locking and the later lines have no font locking, simply appearing as white text. 

Is this expected behaviour, or are all (or none?) of the lines supposed to have the same text properties as the buffer being searched over?

**Comment by zalky** [comment]
Seeing this same behaviour. Font-locking stops halfway down the results page.

**Comment by quicknir** [comment]
Seeing the same issue.

**Comment by peterwvj** [comment]
I'm experiencing this too!

**Comment by cireu** [comment]
Confirmed, I think using swiper-like font lock ensure can fix this

**Comment by cireu** [comment]
@peterwvj  @quicknir  @zalky Can you help test PR https://github.com/emacsorphanage/helm-swoop/pull/165 ?

In this PR, `helm-swoop` will force ensure font-lock before getting contents, however, in large file(buffer size > 100000) this mechanism will be closed for performance.

If you have any idea on this threshold, feel free to tell me.
