### ISSUE TITLE
multi-line does not behave as in screencast

### ISSUE THREAD

**Issue by sandos** [emacsorphanage/helm-swoop#87]
In my current install I only see a multi-line region in the original buffer, but not in the swoop buffer. See attached image.

![image](https://cloud.githubusercontent.com/assets/60831/11424347/8eb0f436-944c-11e5-8e1c-2dc7139f3c28.png)

**Comment by ShingoFukuyama** [comment]
Thank you for reporting with the image. Is this still behave like this?

**Comment by sandos** [comment]
No, it seems to work fine now! Thank you!
